### ISSUE TITLE
AutoAuth not working with firefox version 57

### ISSUE THREAD

**Issue by kasidkhansbp** [steffanschlein/AutoAuth#1]
AutoAuth not working with firefox version 57. Even though it shows ( add to firefox button is present for the AutoAuth ad-on)I am able to add it to my firefox but it does not work. Any idea how to go around it?

**Comment by kasidkhansbp** [comment]
![autoauth](https://user-images.githubusercontent.com/8575030/33280292-7f6a5042-d399-11e7-8c47-5fe54a7e34ce.png)

**Comment by steffanschlein** [comment]
What exactly happens after you add the addon? Does it show up in the addons overview? Also the console log after loading the addon when trying to open a basic auth protected web page would be helpful.
