### ISSUE TITLE
Update to Version 3.0 or newer breaks

### ISSUE THREAD

**Issue by brycelelbach** [steffanschlein/AutoAuth#2]
I'm using Firefox 52.4.0 (ESR) on Debian Linux. I was previously using AuthAuth version 2.1.1,  but recently updated to 3.0 and then 3.1. Both 3.0 and 3.1 do not work for me; when I go to a page with an HTTP password prompt with credentials saved by my password manager, the credentials are autofilled, but AutoAuth no longer submits them automatically. I've had to revert back to AutoAuth 2.1.1 (which works).

**Comment by steffanschlein** [comment]
I am sorry for the inconvenience. The update originally was intended only for Firefox 57+ as WebExtension is required from this version on. I have changed the compatibility to Firefox 57+ now.
