### ISSUE TITLE
Using same credential for one host with multiple ports

### ISSUE THREAD

**Issue by tithom** [steffanschlein/AutoAuth#3]
Hi,
Can you add the possibilities to have one credential for all the ports of one host ?
Like add a checkbox beside the submit button "use these credentials for all ports of this server".
That could save me hundreds of configuration.

**Comment by tithom** [comment]
I have developed the functionality.
http://tithom.fr/upd/autoauth/
> Three files changed, auth.js + modal.html + modal.js (regroup in the zip). There is also the patch file if you prefer. 

Not sure if the double access to the local storage is the fastest way.
I include the modification of the other issue.

**Comment by steffanschlein** [comment]
Thanks for your suggestion. I have merged your patch for #6 but implemented the feature of this issue differently. The user is asked is he wants to save the credentials for all ports only when using a non default port. I think this sould be more conventient for most users.

The update is published as beta version for now:
- https://addons.mozilla.org/de/firefox/addon/autoauth/versions/beta
- https://github.com/steffanschlein/AutoAuth/releases/tag/v3.1.0beta1

If you could test the version, that would be great.

**Comment by tithom** [comment]
Yes it's better to mask the new field on port 80, it will not disturb the general use of the add-on.
And good thing the storage can be access with a list.

It seems perfect thank you !

**Comment by tithom** [comment]
I don't realize if it takes time to modify the option page. Probably.

Like having an option to check by default the all port checkbox.
Another option to have the choice to sort the server by name or by add time.
Another option to modify multiple passwords at one time depending of the host/oldpasswd/username.
One button to delete all save credentials, one to delete all exceptions.

For now these options will not be very useful to me, so I will not create an issue for it.
The delete option and sort option would have been useful just for the change with this beta, but now it's done.
I don't use the add-on for host with changing password (security).
Perhaps just the default check on the checkbox could still be useful. If you are motivated you can just create an about:config entry like "extensions.autoAuth.defaultAllPortChecked=false" and I will turn it to true :)

**Comment by steffanschlein** [comment]
Thanks for the suggestions. I may implement some of them if a have the time.

**Comment by tithom** [comment]
Still no bug with two weeks of using it. You can probably release the version.
It's perfect, if I configure to use the same pass, but there is a different pass for one port, the addon still ask for password (since first attempt failed), so we can configure a different password specifically for one port without removing the * configuration (thanks to the priority).

I have thought about another thing. Having the possibility to disable the add-on on private browsing. Why ? To have a possibility to connect with another username without turn off the add-on.
