### ISSUE TITLE
Button Submit/Cancel acting the same way

### ISSUE THREAD

**Issue by tithom** [steffanschlein/AutoAuth#4]
Whatever the button click, it's the same:
- if the credentials are filled, they both act like the submit button should act
- if the credentials are empty, they both act like the Cancel/Ignore button should act

Since I have saved credentials on the add-on credentials page to have a default credential configuration (I don't want that to change), the credentials fields are pre-filled. 
So I must empty the credentials fields before ignoring a host. Can you change that ?
If it was intended to simplify the process by having one action, perhaps you can detect the fields are unchanged when clicking on Cancel/Ignore ?

**Comment by steffanschlein** [comment]
Version 3.0.2 should fix the bug causing the buttons to act the same.
