### ISSUE TITLE
Save username and password for proxy

### ISSUE THREAD

**Issue by ghost** [steffanschlein/AutoAuth#7]
Hello,
I´m using Ubuntu 17.10, Firefox Quantum 57.0.4 (64-bit) with this add-on. I want to save my proxy credentials but is not working. What can i do? 

Thanks

**Comment by steffanschlein** [comment]
This addon only provides credentials for http basic auth on webpages. If you want to save credentials of proxy servers, I can recommend [FoxyProxy](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/).

**Comment by sfmarques** [comment]
Thanks
